/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ChaptersChapterRouteImport } from './routes/chapters.$chapter'
import { Route as StruggleSlugRouteImport } from './routes/struggle.$slug'
import { Route as VerseChapterVerseRouteImport } from './routes/verse.$chapter.$verse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterRoute = ChaptersChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => ChaptersRoute,
} as any)
const StruggleSlugRoute = StruggleSlugRouteImport.update({
  id: '/struggle/$slug',
  path: '/struggle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerseChapterVerseRoute = VerseChapterVerseRouteImport.update({
  id: '/verse/$chapter/$verse',
  path: '/verse/$chapter/$verse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/daily': typeof DailyRoute
  '/saved': typeof SavedRoute
  '/chapters/$chapter': typeof ChaptersChapterRoute
  '/struggle/$slug': typeof StruggleSlugRoute
  '/verse/$chapter/$verse': typeof VerseChapterVerseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/daily': typeof DailyRoute
  '/saved': typeof SavedRoute
  '/chapters/$chapter': typeof ChaptersChapterRoute
  '/struggle/$slug': typeof StruggleSlugRoute
  '/verse/$chapter/$verse': typeof VerseChapterVerseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/daily': typeof DailyRoute
  '/saved': typeof SavedRoute
  '/chapters/$chapter': typeof ChaptersChapterRoute
  '/struggle/$slug': typeof StruggleSlugRoute
  '/verse/$chapter/$verse': typeof VerseChapterVerseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chapters'
    | '/daily'
    | '/saved'
    | '/chapters/$chapter'
    | '/struggle/$slug'
    | '/verse/$chapter/$verse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chapters'
    | '/daily'
    | '/saved'
    | '/chapters/$chapter'
    | '/struggle/$slug'
    | '/verse/$chapter/$verse'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chapters'
    | '/daily'
    | '/saved'
    | '/chapters/$chapter'
    | '/struggle/$slug'
    | '/verse/$chapter/$verse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  DailyRoute: typeof DailyRoute
  SavedRoute: typeof SavedRoute
  StruggleSlugRoute: typeof StruggleSlugRoute
  VerseChapterVerseRoute: typeof VerseChapterVerseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapter': {
      id: '/chapters/$chapter'
      path: '/$chapter'
      fullPath: '/chapters/$chapter'
      preLoaderRoute: typeof ChaptersChapterRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/struggle/$slug': {
      id: '/struggle/$slug'
      path: '/struggle/$slug'
      fullPath: '/struggle/$slug'
      preLoaderRoute: typeof StruggleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verse/$chapter/$verse': {
      id: '/verse/$chapter/$verse'
      path: '/verse/$chapter/$verse'
      fullPath: '/verse/$chapter/$verse'
      preLoaderRoute: typeof VerseChapterVerseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChaptersRouteChildren {
  ChaptersChapterRoute: typeof ChaptersChapterRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersChapterRoute: ChaptersChapterRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  DailyRoute: DailyRoute,
  SavedRoute: SavedRoute,
  StruggleSlugRoute: StruggleSlugRoute,
  VerseChapterVerseRoute: VerseChapterVerseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
